### ISSUE TITLE
PDP: Show similar products (Admin)

### ISSUE THREAD

**Issue by prinzdezibel** [reactioncommerce/reaction-swag-shop#18]
## "You might also like" grid for product detail page

As an admin you want to somehow correlate products to each other in a way they can be used for displaying the "You might also like" grid on page PDP.

**Comment by zenweasel** [comment]
So I think this should be implemented as a flag on tags (can be done in "metadata" I believe) that it is a "related_product" tag and when one product with that is shown, all other products with that same tag are shown as a "related product". I think we can do without an admin portion for now but maybe we could add some sort of `type` attribute to tags so that we could filter them out in nav admin for core?
