### ISSUE TITLE
Blank screen running on 1.15.0

### ISSUE THREAD

**Issue by stunjiturner** [reactioncommerce/reaction-swag-shop#73]
During testing against the latest master branch a blank screen shows, with no errors in the browser javascript console

**Comment by lortschi** [comment]
The same by me too.

# versions
Node: 9.4.0
NPM: 6.0.1
Meteor Node: 8.11.3
Meteor NPM: 5.10.0
Reaction CLI: 0.29.0
Reaction: 1.15.0
Reaction branch: master

**Comment by stunjiturner** [comment]
working on it now!

**Comment by zenweasel** [comment]
This is coming from Reaction core, not this plugin. Closing

**Comment by stunjiturner** [comment]
Any ideas I been chasing the solution all day? I took the little info from the Heroku deployment js console log, but the renderShopSelect() does not seem to be the problem, because even when I take out the method call the same thing happens

S Tunji Turner
sightuary
@sightuary

**Comment by zenweasel** [comment]
I tried tracking this down yesterday by running a fresh install and a migrated install side-by-side but I couldn't really see any differences. Also I don't see the error you see so I suspect that may be from your code or this plugin not from core.

It probably has to do with Shops somehow for it to render absolutely nothing, rather than say an empty product grid.

**Comment by zenweasel** [comment]
Also, we should try to keep all discussion re: this issue in the GH issue in Reaction proper as no one will see this here.
